FROM ruby:2.7.2-alpine3.12

RUN gem install bundler:2.1.4

RUN apk update --no-cache && \
    apk add build-base postgresql-dev git nodejs yarn tzdata bash sqlite-dev npm && \
    mkdir -p /app

# https://github.com/pry/pry/issues/1248
RUN apk --update add less

WORKDIR /app

COPY ./lib/ /app/lib/
COPY matestack-ui-core.gemspec /app/
COPY Gemfile* /app/
RUN bundle install

COPY package.json yarn* /app/
RUN yarn install
